# -*- coding: utf-8 -*-
"""Password Authentication using Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PyWoQOPlS9C_Q5-Iu8Xb3e2_Cdnixdyg
"""

import getpass
database = {"dipta": "976729", "banik": "2502"}
username = input("Enter Your Username : ")
password = getpass. getpass("Enter Your Password: ")
for i in database. keys():
  if username == i:
    while password != database.get(i):
      password = getpass.getpass("Enter Your Password Again : ")
      break
print ("Verified" )